env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-param-reassign:
    - error
  no-extra-bind:
    - error
  no-eq-null:
    - error
  no-extend-native:
    - error
  no-implicit-coercion:
    - error
  no-loss-of-precision:
    - error
  no-extra-boolean-cast:
    - error
  yoda:
    - error
